blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/fturkyilmaz/openiddict-dotnet-core-custom-identity-server/docs
    about: Please check the documentation before opening a new issue.
